"""empty message

Revision ID: 1d5b752175a5
Revises: 7827d05cd7d9
Create Date: 2020-05-03 22:09:12.367994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5b752175a5'
down_revision = '7827d05cd7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('descripcion', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'descripcion')
    # ### end Alembic commands ###
