"""empty message

Revision ID: 4dc43fba3cb1
Revises: 1d5b752175a5
Create Date: 2020-05-09 19:24:28.464276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc43fba3cb1'
down_revision = '1d5b752175a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('ppi', sa.String(length=50), nullable=True),
    sa.Column('rava', sa.String(length=50), nullable=True),
    sa.Column('iol', sa.String(length=50), nullable=True),
    sa.Column('follow', sa.Boolean(), nullable=True),
    sa.Column('descricion', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
