"""empty message

Revision ID: 7827d05cd7d9
Revises: c56576a50993
Create Date: 2020-05-03 16:41:06.527623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7827d05cd7d9'
down_revision = 'c56576a50993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price_usd', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('profit_amount_usd', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('sell_price_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sell_price_usd')
    op.drop_column('orders', 'profit_amount_usd')
    op.drop_column('orders', 'price_usd')
    # ### end Alembic commands ###
