"""empty message

Revision ID: 986015a5d4f7
Revises: a439ba4a0903
Create Date: 2020-05-02 12:04:19.428973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '986015a5d4f7'
down_revision = 'a439ba4a0903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('type2', sa.String(length=3), nullable=True))
    op.drop_column('orders', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'type2')
    # ### end Alembic commands ###
