"""empty message

Revision ID: c56576a50993
Revises: 986015a5d4f7
Create Date: 2020-05-02 12:08:21.212381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c56576a50993'
down_revision = '986015a5d4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('type', sa.String(length=3), nullable=True))
    op.drop_column('orders', 'type2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('type2', mysql.VARCHAR(length=3), nullable=True))
    op.drop_column('orders', 'type')
    # ### end Alembic commands ###
