"""empty message

Revision ID: d7ac15e971cc
Revises: 
Create Date: 2020-07-14 10:13:03.753690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ac15e971cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('ppi', sa.String(length=50), nullable=True),
    sa.Column('rava', sa.String(length=50), nullable=True),
    sa.Column('iol', sa.String(length=50), nullable=True),
    sa.Column('follow', sa.Boolean(), nullable=True),
    sa.Column('descricion', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=7), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('profit_amount', sa.Float(), nullable=True),
    sa.Column('profit_amount_usd', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_date', sa.DateTime(), nullable=True),
    sa.Column('sell_price_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dolar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiker', sa.String(length=60), nullable=True),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('boleto_id', sa.Integer(), nullable=True),
    sa.Column('dolar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alycs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('contraparte', sa.Integer(), nullable=True),
    sa.Column('commitent', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boleto_nro', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo_operacion', sa.String(length=3), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=2), nullable=True),
    sa.Column('tipo_cambio', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('alyc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alyc_id'], ['alycs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('fecha_concertacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_liquidacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_operacion', sa.String(length=3), nullable=True),
    sa.Column('tiker', sa.String(length=10), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_promedio', sa.Float(), nullable=True),
    sa.Column('bruto', sa.Float(), nullable=True),
    sa.Column('arancel', sa.Float(), nullable=True),
    sa.Column('perc_arancel', sa.Float(), nullable=True),
    sa.Column('mercado_importe', sa.Float(), nullable=True),
    sa.Column('neto', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=2), nullable=True),
    sa.Column('tipo_cambio_arancel', sa.Float(), nullable=True),
    sa.Column('tipo_cambio', sa.Float(), nullable=True),
    sa.Column('iva', sa.Boolean(), nullable=True),
    sa.Column('interes', sa.Float(), nullable=True),
    sa.Column('alyc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alyc_id'], ['alycs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('movements')
    op.drop_table('alycs')
    op.drop_table('shares')
    op.drop_table('portfolios')
    op.drop_table('orders')
    op.drop_table('follow')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
